# Generated by Django 5.2.5 on 2026-01-01 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_orderproduct_color_remove_orderproduct_size_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='paymnent',
            new_name='payment',
        ),
    ]
