# Generated by Django 5.2.5 on 2026-01-08 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_rename_paymnent_orderproduct_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction_uuid',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
